# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
sk:
  languageCode: sk-sk
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/sk
  menu:
   main:
     - name: Úvod
       url: '/'
       weight: 1
     - name: Môj príbeh
       url: '/about'
       weight: 2
     - name: Služby
       url: '/services'
       weight: 3
     - name: Koučing
       parent: Služby
       url: '/coaching'
       weight: 1
     - name: Mentoring
       parent: Služby
       url: '/mentoring'
       weight: 2
     - name: Školenia
       parent: Služby
       url: '/trainings'
       weight: 3
     - name: Referencie
       url: '/references'
       weight: 4
    #  - name: Blog
    #    url: '/blog'
    #    weight: 5
     - name: Kontakt
       url: '/contact'
       weight: 6


# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
  title: Stanislav Valasek
  params:
    description: Mentoring, coaching, communication, management trainings

    header:
      navbar:
        logo:
          # Logo text
          text: "Your authenticity is important"
  
  menu:
    main:
      - name: My Story
        url: '/about'
        weight: 2
      - name: Services
        url: '/services'
        weight: 3
      - name: Coaching
        parent: Services
        url: '/en/coaching'
        weight: 1
      - name: Mentoring
        parent: Services
        url: '/en/mentoring'
        weight: 2
      - name: Trainings
        parent: Services
        url: '/trainings'
        weight: 3
      - name: References
        url: '/references'
        weight: 4
      - name: Blog
        url: 'blog'
        weight: 5
      - name: Contact
        url: '/contact'
        weight: 6
